/* Generated By:JJTree: Do not edit this line. ASTBoolValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTBoolValue extends SimpleNode {
  private String value;
  public ASTBoolValue(int id) {
    super(id);
  }

  public ASTBoolValue(Parser p, int id) {
    super(p, id);
  }

  public void setValue(final String value) {
    this.value = value;
  }

  public String getValue() {
    return this.value;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=8407f537804e3bcc81ee1e48090fc28e (do not edit this line) */
