/* Generated By:JJTree: Do not edit this line. ASTRealValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTRealValue extends SimpleNode {
  public ASTRealValue(int id) {
    super(id);
  }

  public ASTRealValue(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  private String m_value;
  public void setValue(String v) { m_value = v; }
  public String getValue() { return m_value; }
}
/* JavaCC - OriginalChecksum=2250655958988ac9530e8cb9bbbdbe10 (do not edit this line) */
