/* Generated By:JJTree: Do not edit this line. ASTStringValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTStringValue extends SimpleNode {
  public ASTStringValue(int id) {
    super(id);
  }

  public ASTStringValue(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  private String m_value = "";
  public void setValue(String v) { m_value = v; }
  public String getValue() { return m_value; }

}
/* JavaCC - OriginalChecksum=895eff4348fcc4ca0482be5035af310c (do not edit this line) */
